services:
  postgres:
    image: postgres:16
    container_name: postgres_quiniela
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_quiniela
    restart: always
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpiresInMinutes: ${JWT_EXPIRES_IN_MINUTES}
      Resend__ApiKey: ${RESEND_API_KEY}
      Crypto__Key: ${CRYPTO_KEY}
      Crypto__IV: ${CRYPTO_IV}
    ports:
      - "8080:8080"

volumes:
  postgres_data: