--
-- PostgreSQL database dump
--

\restrict p0EUCLdrHGVToxl0IhLbAE3I20rUSJfdtat9hN3aAghmEjGUI3Tcq5qIcPKsKR7

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fn_audit_log(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_audit_log() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_logs (tabla, operacion, valor_anterior, valor_nuevo, user_id, fecha_hora)
        VALUES (
            TG_TABLE_NAME,
            'INSERT',
            NULL,
            to_jsonb(NEW),
            (to_jsonb(NEW)->>'Id')::int,
            NOW()
        );
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_logs (tabla, operacion, valor_anterior, valor_nuevo, user_id, fecha_hora)
        VALUES (
            TG_TABLE_NAME,
            'UPDATE',
            to_jsonb(OLD),
            to_jsonb(NEW),
            (to_jsonb(NEW)->>'Id')::int,
            NOW()
        );
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit_logs (tabla, operacion, valor_anterior, valor_nuevo, user_id, fecha_hora)
        VALUES (
            TG_TABLE_NAME,
            'DELETE',
            to_jsonb(OLD),
            NULL,
            (to_jsonb(OLD)->>'Id')::int,
            NOW()
        );
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ClasificacionGrupos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ClasificacionGrupos" (
    "Id" integer NOT NULL,
    "GrupoId" integer NOT NULL,
    "EquipoId" integer NOT NULL,
    "PartidosJugados" integer NOT NULL,
    "Ganados" integer NOT NULL,
    "Empatados" integer NOT NULL,
    "Perdidos" integer NOT NULL,
    "GolesAFavor" integer NOT NULL,
    "GolesEnContra" integer NOT NULL,
    "DiferenciaGoles" integer NOT NULL,
    "Puntos" integer NOT NULL
);


--
-- Name: ClasificacionGrupos_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ClasificacionGrupos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ClasificacionGrupos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Equipos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Equipos" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "CodigoFifa" text NOT NULL,
    "BanderaUrl" text NOT NULL,
    "Capitan" text DEFAULT ''::text NOT NULL,
    "Entrenador" text DEFAULT ''::text NOT NULL
);


--
-- Name: Equipos_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Equipos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Equipos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Estadios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Estadios" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Ciudad" text NOT NULL,
    "Pais" text NOT NULL,
    "Capacidad" integer NOT NULL
);


--
-- Name: Estadio_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Estadios" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Estadio_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Fases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Fases" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Orden" integer NOT NULL,
    "TorneoId" integer NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


--
-- Name: Fases_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Fases" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Fases_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GrupoEquipos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GrupoEquipos" (
    "GrupoId" integer NOT NULL,
    "EquipoId" integer NOT NULL
);


--
-- Name: Grupos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Grupos" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "TorneoId" integer NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


--
-- Name: Grupos_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Grupos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Grupos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvitacionesLiga; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."InvitacionesLiga" (
    "Id" integer NOT NULL,
    "LigaId" integer NOT NULL,
    "EmailInvitado" text NOT NULL,
    "UserId" integer,
    "Token" text NOT NULL,
    "Estado" integer NOT NULL,
    "FechaEnvio" timestamp with time zone NOT NULL,
    "FechaExpiracion" timestamp with time zone,
    "FechaRespuesta" timestamp with time zone,
    "DeletedAt" timestamp with time zone
);


--
-- Name: InvitacionesLiga_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."InvitacionesLiga" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvitacionesLiga_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LigaMiembros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LigaMiembros" (
    "UserId" integer NOT NULL,
    "LigaId" integer NOT NULL,
    "EsAdmin" boolean NOT NULL,
    "Puntos" integer NOT NULL,
    "FechaUnion" timestamp with time zone NOT NULL,
    "NombreEquipo" text DEFAULT ''::text NOT NULL,
    "Estado" integer DEFAULT 0 NOT NULL,
    "DeletedAt" timestamp with time zone
);


--
-- Name: Ligas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Ligas" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "EsDeApuestas" boolean NOT NULL,
    "PrecioPorUnirse" numeric,
    "TorneoId" integer NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone
);


--
-- Name: Ligas_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Ligas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ligas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Partidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Partidos" (
    "Id" integer NOT NULL,
    "TorneoId" integer NOT NULL,
    "FaseId" integer NOT NULL,
    "GrupoId" integer,
    "EquipoLocalId" integer,
    "EquipoVisitanteId" integer,
    "FechaHora" timestamp with time zone NOT NULL,
    "GolesLocal" integer,
    "GolesVisitante" integer,
    "Finalizado" boolean NOT NULL,
    "EstadioId" integer DEFAULT 0 NOT NULL,
    "DescripcionLocal" text,
    "DescripcionVisitante" text,
    "DeletedAt" timestamp with time zone,
    "GolesLocalPenales" integer,
    "GolesVisitantePenales" integer
);


--
-- Name: Partidos_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Partidos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Partidos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PasswordResetTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PasswordResetTokens" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Usado" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: PasswordResetTokens_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PasswordResetTokens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PasswordResetTokens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Predicciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Predicciones" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "LigaId" integer NOT NULL,
    "PartidoId" integer NOT NULL,
    "GolesLocal" integer NOT NULL,
    "GolesVisitante" integer NOT NULL,
    "PuntosGanados" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone
);


--
-- Name: Prediccion_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Predicciones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Prediccion_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PremiosDistribuidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PremiosDistribuidos" (
    "Id" integer NOT NULL,
    "TorneoId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "LigaId" integer,
    "Concepto" text NOT NULL,
    "Monto" numeric NOT NULL,
    "Posicion" integer NOT NULL,
    "FechaDistribucion" timestamp with time zone NOT NULL
);


--
-- Name: PremiosDistribuidos_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PremiosDistribuidos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PremiosDistribuidos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Name" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


--
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Torneos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Torneos" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Año" integer NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "PaisSede" text DEFAULT ''::text NOT NULL,
    "Finalizado" boolean DEFAULT false NOT NULL
);


--
-- Name: Torneos_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Torneos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Torneos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserSessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserSessions" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "IpOrigen" text NOT NULL,
    "UserAgent" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "ClosedAt" timestamp with time zone,
    "Estado" integer NOT NULL
);


--
-- Name: UserSessions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."UserSessions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserSessions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RoleId" integer NOT NULL,
    "DeletedAt" timestamp with time zone
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    "Id" bigint NOT NULL,
    tabla text NOT NULL,
    operacion text NOT NULL,
    valor_anterior jsonb,
    valor_nuevo jsonb,
    user_id integer,
    fecha_hora timestamp with time zone NOT NULL
);


--
-- Name: audit_logs_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."audit_logs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ClasificacionGrupos PK_ClasificacionGrupos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClasificacionGrupos"
    ADD CONSTRAINT "PK_ClasificacionGrupos" PRIMARY KEY ("Id");


--
-- Name: Equipos PK_Equipos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Equipos"
    ADD CONSTRAINT "PK_Equipos" PRIMARY KEY ("Id");


--
-- Name: Estadios PK_Estadios; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Estadios"
    ADD CONSTRAINT "PK_Estadios" PRIMARY KEY ("Id");


--
-- Name: Fases PK_Fases; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Fases"
    ADD CONSTRAINT "PK_Fases" PRIMARY KEY ("Id");


--
-- Name: GrupoEquipos PK_GrupoEquipos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GrupoEquipos"
    ADD CONSTRAINT "PK_GrupoEquipos" PRIMARY KEY ("GrupoId", "EquipoId");


--
-- Name: Grupos PK_Grupos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Grupos"
    ADD CONSTRAINT "PK_Grupos" PRIMARY KEY ("Id");


--
-- Name: InvitacionesLiga PK_InvitacionesLiga; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvitacionesLiga"
    ADD CONSTRAINT "PK_InvitacionesLiga" PRIMARY KEY ("Id");


--
-- Name: LigaMiembros PK_LigaMiembros; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LigaMiembros"
    ADD CONSTRAINT "PK_LigaMiembros" PRIMARY KEY ("UserId", "LigaId");


--
-- Name: Ligas PK_Ligas; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ligas"
    ADD CONSTRAINT "PK_Ligas" PRIMARY KEY ("Id");


--
-- Name: Partidos PK_Partidos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "PK_Partidos" PRIMARY KEY ("Id");


--
-- Name: PasswordResetTokens PK_PasswordResetTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PasswordResetTokens"
    ADD CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id");


--
-- Name: Predicciones PK_Predicciones; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Predicciones"
    ADD CONSTRAINT "PK_Predicciones" PRIMARY KEY ("Id");


--
-- Name: PremiosDistribuidos PK_PremiosDistribuidos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PremiosDistribuidos"
    ADD CONSTRAINT "PK_PremiosDistribuidos" PRIMARY KEY ("Id");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- Name: Torneos PK_Torneos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Torneos"
    ADD CONSTRAINT "PK_Torneos" PRIMARY KEY ("Id");


--
-- Name: UserSessions PK_UserSessions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSessions"
    ADD CONSTRAINT "PK_UserSessions" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: audit_logs PK_audit_logs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id");


--
-- Name: IX_ClasificacionGrupos_EquipoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ClasificacionGrupos_EquipoId" ON public."ClasificacionGrupos" USING btree ("EquipoId");


--
-- Name: IX_ClasificacionGrupos_GrupoId_EquipoId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ClasificacionGrupos_GrupoId_EquipoId" ON public."ClasificacionGrupos" USING btree ("GrupoId", "EquipoId");


--
-- Name: IX_Fases_TorneoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Fases_TorneoId" ON public."Fases" USING btree ("TorneoId");


--
-- Name: IX_GrupoEquipos_EquipoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GrupoEquipos_EquipoId" ON public."GrupoEquipos" USING btree ("EquipoId");


--
-- Name: IX_Grupos_TorneoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Grupos_TorneoId" ON public."Grupos" USING btree ("TorneoId");


--
-- Name: IX_InvitacionesLiga_LigaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvitacionesLiga_LigaId" ON public."InvitacionesLiga" USING btree ("LigaId");


--
-- Name: IX_InvitacionesLiga_Token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_InvitacionesLiga_Token" ON public."InvitacionesLiga" USING btree ("Token");


--
-- Name: IX_InvitacionesLiga_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvitacionesLiga_UserId" ON public."InvitacionesLiga" USING btree ("UserId");


--
-- Name: IX_LigaMiembros_LigaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_LigaMiembros_LigaId" ON public."LigaMiembros" USING btree ("LigaId");


--
-- Name: IX_Ligas_CreatedByUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Ligas_CreatedByUserId" ON public."Ligas" USING btree ("CreatedByUserId");


--
-- Name: IX_Ligas_TorneoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Ligas_TorneoId" ON public."Ligas" USING btree ("TorneoId");


--
-- Name: IX_Partidos_EquipoLocalId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Partidos_EquipoLocalId" ON public."Partidos" USING btree ("EquipoLocalId");


--
-- Name: IX_Partidos_EquipoVisitanteId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Partidos_EquipoVisitanteId" ON public."Partidos" USING btree ("EquipoVisitanteId");


--
-- Name: IX_Partidos_EstadioId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Partidos_EstadioId" ON public."Partidos" USING btree ("EstadioId");


--
-- Name: IX_Partidos_FaseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Partidos_FaseId" ON public."Partidos" USING btree ("FaseId");


--
-- Name: IX_Partidos_GrupoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Partidos_GrupoId" ON public."Partidos" USING btree ("GrupoId");


--
-- Name: IX_Partidos_TorneoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Partidos_TorneoId" ON public."Partidos" USING btree ("TorneoId");


--
-- Name: IX_PasswordResetTokens_Token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_PasswordResetTokens_Token" ON public."PasswordResetTokens" USING btree ("Token");


--
-- Name: IX_PasswordResetTokens_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PasswordResetTokens_UserId" ON public."PasswordResetTokens" USING btree ("UserId");


--
-- Name: IX_Predicciones_LigaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Predicciones_LigaId" ON public."Predicciones" USING btree ("LigaId");


--
-- Name: IX_Predicciones_PartidoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Predicciones_PartidoId" ON public."Predicciones" USING btree ("PartidoId");


--
-- Name: IX_Predicciones_UserId_LigaId_PartidoId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Predicciones_UserId_LigaId_PartidoId" ON public."Predicciones" USING btree ("UserId", "LigaId", "PartidoId");


--
-- Name: IX_PremiosDistribuidos_LigaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PremiosDistribuidos_LigaId" ON public."PremiosDistribuidos" USING btree ("LigaId");


--
-- Name: IX_PremiosDistribuidos_TorneoId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PremiosDistribuidos_TorneoId" ON public."PremiosDistribuidos" USING btree ("TorneoId");


--
-- Name: IX_PremiosDistribuidos_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PremiosDistribuidos_UserId" ON public."PremiosDistribuidos" USING btree ("UserId");


--
-- Name: IX_UserSessions_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserSessions_UserId" ON public."UserSessions" USING btree ("UserId");


--
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- Name: Ligas trg_audit_ligas; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_audit_ligas AFTER INSERT OR DELETE OR UPDATE ON public."Ligas" FOR EACH ROW EXECUTE FUNCTION public.fn_audit_log();


--
-- Name: Partidos trg_audit_partidos; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_audit_partidos AFTER INSERT OR DELETE OR UPDATE ON public."Partidos" FOR EACH ROW EXECUTE FUNCTION public.fn_audit_log();


--
-- Name: Predicciones trg_audit_predicciones; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_audit_predicciones AFTER INSERT OR DELETE OR UPDATE ON public."Predicciones" FOR EACH ROW EXECUTE FUNCTION public.fn_audit_log();


--
-- Name: Users trg_audit_users; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_audit_users AFTER INSERT OR DELETE OR UPDATE ON public."Users" FOR EACH ROW EXECUTE FUNCTION public.fn_audit_log();


--
-- Name: ClasificacionGrupos FK_ClasificacionGrupos_Equipos_EquipoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClasificacionGrupos"
    ADD CONSTRAINT "FK_ClasificacionGrupos_Equipos_EquipoId" FOREIGN KEY ("EquipoId") REFERENCES public."Equipos"("Id") ON DELETE RESTRICT;


--
-- Name: ClasificacionGrupos FK_ClasificacionGrupos_Grupos_GrupoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClasificacionGrupos"
    ADD CONSTRAINT "FK_ClasificacionGrupos_Grupos_GrupoId" FOREIGN KEY ("GrupoId") REFERENCES public."Grupos"("Id") ON DELETE CASCADE;


--
-- Name: Fases FK_Fases_Torneos_TorneoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Fases"
    ADD CONSTRAINT "FK_Fases_Torneos_TorneoId" FOREIGN KEY ("TorneoId") REFERENCES public."Torneos"("Id") ON DELETE CASCADE;


--
-- Name: GrupoEquipos FK_GrupoEquipos_Equipos_EquipoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GrupoEquipos"
    ADD CONSTRAINT "FK_GrupoEquipos_Equipos_EquipoId" FOREIGN KEY ("EquipoId") REFERENCES public."Equipos"("Id") ON DELETE CASCADE;


--
-- Name: GrupoEquipos FK_GrupoEquipos_Grupos_GrupoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GrupoEquipos"
    ADD CONSTRAINT "FK_GrupoEquipos_Grupos_GrupoId" FOREIGN KEY ("GrupoId") REFERENCES public."Grupos"("Id") ON DELETE CASCADE;


--
-- Name: Grupos FK_Grupos_Torneos_TorneoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Grupos"
    ADD CONSTRAINT "FK_Grupos_Torneos_TorneoId" FOREIGN KEY ("TorneoId") REFERENCES public."Torneos"("Id") ON DELETE CASCADE;


--
-- Name: InvitacionesLiga FK_InvitacionesLiga_Ligas_LigaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvitacionesLiga"
    ADD CONSTRAINT "FK_InvitacionesLiga_Ligas_LigaId" FOREIGN KEY ("LigaId") REFERENCES public."Ligas"("Id") ON DELETE CASCADE;


--
-- Name: InvitacionesLiga FK_InvitacionesLiga_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvitacionesLiga"
    ADD CONSTRAINT "FK_InvitacionesLiga_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: LigaMiembros FK_LigaMiembros_Ligas_LigaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LigaMiembros"
    ADD CONSTRAINT "FK_LigaMiembros_Ligas_LigaId" FOREIGN KEY ("LigaId") REFERENCES public."Ligas"("Id") ON DELETE CASCADE;


--
-- Name: LigaMiembros FK_LigaMiembros_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LigaMiembros"
    ADD CONSTRAINT "FK_LigaMiembros_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Ligas FK_Ligas_Torneos_TorneoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ligas"
    ADD CONSTRAINT "FK_Ligas_Torneos_TorneoId" FOREIGN KEY ("TorneoId") REFERENCES public."Torneos"("Id") ON DELETE CASCADE;


--
-- Name: Ligas FK_Ligas_Users_CreatedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ligas"
    ADD CONSTRAINT "FK_Ligas_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: Partidos FK_Partidos_Equipos_EquipoLocalId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "FK_Partidos_Equipos_EquipoLocalId" FOREIGN KEY ("EquipoLocalId") REFERENCES public."Equipos"("Id") ON DELETE RESTRICT;


--
-- Name: Partidos FK_Partidos_Equipos_EquipoVisitanteId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "FK_Partidos_Equipos_EquipoVisitanteId" FOREIGN KEY ("EquipoVisitanteId") REFERENCES public."Equipos"("Id") ON DELETE RESTRICT;


--
-- Name: Partidos FK_Partidos_Estadios_EstadioId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "FK_Partidos_Estadios_EstadioId" FOREIGN KEY ("EstadioId") REFERENCES public."Estadios"("Id") ON DELETE RESTRICT;


--
-- Name: Partidos FK_Partidos_Fases_FaseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "FK_Partidos_Fases_FaseId" FOREIGN KEY ("FaseId") REFERENCES public."Fases"("Id") ON DELETE RESTRICT;


--
-- Name: Partidos FK_Partidos_Grupos_GrupoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "FK_Partidos_Grupos_GrupoId" FOREIGN KEY ("GrupoId") REFERENCES public."Grupos"("Id") ON DELETE SET NULL;


--
-- Name: Partidos FK_Partidos_Torneos_TorneoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Partidos"
    ADD CONSTRAINT "FK_Partidos_Torneos_TorneoId" FOREIGN KEY ("TorneoId") REFERENCES public."Torneos"("Id") ON DELETE RESTRICT;


--
-- Name: PasswordResetTokens FK_PasswordResetTokens_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PasswordResetTokens"
    ADD CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Predicciones FK_Predicciones_Ligas_LigaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Predicciones"
    ADD CONSTRAINT "FK_Predicciones_Ligas_LigaId" FOREIGN KEY ("LigaId") REFERENCES public."Ligas"("Id") ON DELETE RESTRICT;


--
-- Name: Predicciones FK_Predicciones_Partidos_PartidoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Predicciones"
    ADD CONSTRAINT "FK_Predicciones_Partidos_PartidoId" FOREIGN KEY ("PartidoId") REFERENCES public."Partidos"("Id") ON DELETE RESTRICT;


--
-- Name: Predicciones FK_Predicciones_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Predicciones"
    ADD CONSTRAINT "FK_Predicciones_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: PremiosDistribuidos FK_PremiosDistribuidos_Ligas_LigaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PremiosDistribuidos"
    ADD CONSTRAINT "FK_PremiosDistribuidos_Ligas_LigaId" FOREIGN KEY ("LigaId") REFERENCES public."Ligas"("Id") ON DELETE SET NULL;


--
-- Name: PremiosDistribuidos FK_PremiosDistribuidos_Torneos_TorneoId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PremiosDistribuidos"
    ADD CONSTRAINT "FK_PremiosDistribuidos_Torneos_TorneoId" FOREIGN KEY ("TorneoId") REFERENCES public."Torneos"("Id") ON DELETE RESTRICT;


--
-- Name: PremiosDistribuidos FK_PremiosDistribuidos_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PremiosDistribuidos"
    ADD CONSTRAINT "FK_PremiosDistribuidos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: UserSessions FK_UserSessions_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSessions"
    ADD CONSTRAINT "FK_UserSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict p0EUCLdrHGVToxl0IhLbAE3I20rUSJfdtat9hN3aAghmEjGUI3Tcq5qIcPKsKR7

