// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiniela.Data;

#nullable disable

namespace Quiniela.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314034458_LigaAndTorneo")]
    partial class LigaAndTorneo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quiniela.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsDeApuestas")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecioPorUnirse")
                        .HasColumnType("numeric");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.HasIndex("UserId");

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("Quiniela.Models.LigaMiembro", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("LigaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "LigaId");

                    b.HasIndex("LigaId");

                    b.ToTable("LigaMiembros");
                });

            modelBuilder.Entity("Quiniela.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 14, 3, 44, 58, 44, DateTimeKind.Utc).AddTicks(7134),
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 14, 3, 44, 58, 44, DateTimeKind.Utc).AddTicks(7211),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Quiniela.Models.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("Quiniela.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 14, 3, 44, 58, 161, DateTimeKind.Utc).AddTicks(5862),
                            Email = "admin@quiniela.com",
                            FirstName = "System",
                            LastName = "Admin",
                            Password = "$2a$11$xC0oxge0L2Wwjzy3ZUI8TefV1SKu7nDyzvArYeam/ThyhlONtzD/2",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Quiniela.Models.Liga", b =>
                {
                    b.HasOne("Quiniela.Models.Torneo", "Torneo")
                        .WithMany("Ligas")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quiniela.Models.User", "User")
                        .WithMany("Ligas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Torneo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiniela.Models.LigaMiembro", b =>
                {
                    b.HasOne("Quiniela.Models.Liga", "Liga")
                        .WithMany("LigaMiembros")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quiniela.Models.User", "User")
                        .WithMany("LigaMiembros")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiniela.Models.User", b =>
                {
                    b.HasOne("Quiniela.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Quiniela.Models.Liga", b =>
                {
                    b.Navigation("LigaMiembros");
                });

            modelBuilder.Entity("Quiniela.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Quiniela.Models.Torneo", b =>
                {
                    b.Navigation("Ligas");
                });

            modelBuilder.Entity("Quiniela.Models.User", b =>
                {
                    b.Navigation("LigaMiembros");

                    b.Navigation("Ligas");
                });
#pragma warning restore 612, 618
        }
    }
}
